# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5f71e50451870e78e808e91da99ee88ef9b7cf552df36bf0a6bf31ed800735a06f9e35a8cd84b2c0d5c53a007c6128b4577b7575cd480c8658f9dd149c18b3a

test:
  secret_key_base: 63c4ff7704fee3edcddb7567d8765c9dbe6bcf1e5f968ca0fb5c6524c8ea4fa64ab24df4ba9b4b22a45b8be292b07f2580624c404f0998c835672ebbbf5d835d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 63c4ff7704fee3edcddb7567d8765c9dbe6bcf1e5f968ca0fb5c6524c8ea4fa64ab24df4ba9b4b22a45b8be292b07f2580624c404f0998c835672ebbbf5d835d

